### ISSUE TITLE
'Automatic' accept does not work if user is also using zsh-autosuggestions.

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/fzf-z#14]
It appears that the change introduced by https://github.com/andrewferrier/fzf-z/pull/13 does not work if the user also uses https://github.com/zsh-users/zsh-autosuggestions. On some initial debugging, it looks as if in `should-accept-line()`, `-o auto_cd` does not match, even if the user has it set in their shell (I've checked by running `setopt` directly from my shell - it looks as if running `setopt` inside `should-accept-line` gives different options set from running it in the shell - not just `auto_cd`). I assume `zsh-autosuggestions` is mucking around with the set options somehow, but haven't had time to debug and figure out where the issue lies. @hallettj would be interested in your input given you kindly suggested the change.

**Comment by hallettj** [comment]
Using git bisect I found that the conflict from autosuggestions was introduced in this commit: https://github.com/zsh-users/zsh-autosuggestions/commit/4540304fa0a59b9054f19ede32088da6669938d1

**Comment by hallettj** [comment]
There is a fix for this issue in this PR in zsh-autosuggestions:

https://github.com/zsh-users/zsh-autosuggestions/pull/402

That PR is in the `develop` branch, so I expect that the fix will be included in an updated release of autosuggestions in the near future. There is a workaround given in [issue #379](https://github.com/zsh-users/zsh-autosuggestions/issues/379#issuecomment-445541971):

```
ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=(fzfz-file-widget)
```

I do not recommend that workaround. The expectation is that if you have a suggested completion after the cursor, and you fill a directory path in a non-empty command with fzf-z, the suggested completion should disappear. But with the above workaround the completion does not disappear, and the directory path is inserted between the previously-typed text and the completion text.

My plan is to use the autosuggest develop branch until the next release.

**Comment by andrewferrier** [comment]
@hallettj OK, I tested the workaround. I don't have much issue with it personally, so I intend to use that myself. Agree that for anyone else who doesn't like that, using the `develop` branch of `zsh-autosuggestions` seems like a good alternative for now. I'll keep this bug open for reference, even though it lives over there, until it's fixed in master in `zsh-autosuggestions`. Thanks for all your help!

**Comment by andrewferrier** [comment]
FYI - seems this this bug is resolved now as of the most recent version of `zsh-autosuggestions`. Closing this bug.
