### ISSUE TITLE
Stop leaking global vars or at least namespace them

### ISSUE THREAD

**Issue by z0rc** [andrewferrier/fzf-z#15]
This plugin defines quite a bunch of global shell vars with generic names, which is some edge cases might have unexpected behavior with user's scripts.

Ideally the variables should be kept local for defined functions and exposed to user only if they have meaningful effect, like configuration option. Also it would be nice to organize them under some "namespace", like `FZFZ_`, so there is minimal chance with clashing with user defined vars. Check out https://github.com/zsh-users/zsh-syntax-highlighting and https://github.com/zsh-users/zsh-autosuggestions for reference.

**Comment by andrewferrier** [comment]
That's a very good point, thank you. I've just pushed a change which I think mostly addresses your concern. I'm still relatively new to zsh - it seems that it doesn't have any concept of script-local variables, so the ones at the script level I have prefixed with a "namespace", and the others are now declared as `local`. User-configurable variables are now clearer too. Appreciate any comments you have. Thanks for raising it.
