### ISSUE TITLE
Consider integration with fasd

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/fzf-z#17]
https://github.com/clvv/fasd

**Comment by aaronjensen** [comment]
👍 I'm using this for now: https://github.com/aaronjensen/fzf-fasd-jump 

Thank you for fzf-z! 😄

**Comment by andrewferrier** [comment]
@aaronjensen cool. I'll take a look at that sometime, maybe I can integrate it in?

**Comment by aaronjensen** [comment]
Absolutely, it's just a fork of this repo with a few quick tweaks to make it work w/ fasd since I don't need it to work with z as well.

**Comment by aaronjensen** [comment]
🎊 thanks!

**Comment by andrewferrier** [comment]
@aaronjensen for your awareness, I'm closing this because I've now incorporated this into `fzf-z`; see the README (https://github.com/andrewferrier/fzf-z/blob/master/README.md) - you can set `FZFZ_RECENT_DIRS_TOOL` to `fasd` to use it instead of `z`. Also, I noticed you don't want to use subdirs - I've optimized the use of the `FZFZ_SUBDIR_LIMIT` variable such that if it's set to `0`, it ignores them completely. 

Hope you find this helpful!

**Comment by aaronjensen** [comment]
Oh, that's very cool. Thank you. I'll try it out tomorrow and let you know if I have any trouble.
