### ISSUE TITLE
added 'cd ' in printf (suggestion)

### ISSUE THREAD

**Issue by chew-z** [andrewferrier/fzf-z#2]
Excellent plugin, really.

I have made slight change adding 'cd ' in

`printf 'cd %q ' "$item"`

**Comment by andrewferrier** [comment]
Agreed, that is an improvement, I don't know why I didn't think of something so obvious! I've fixed that in the plugin and pushed an updated version.

**Comment by andrewferrier** [comment]
For the record, I've reverted this change again under #3. I realised that in zsh (as long as you have the AUTO_CD option turned on, which many people do), just typing the name of a directory is enough to change to it; you don't actually need 'cd'. Removing the cd increases the flexibility and usefulness of this plugin; it means you can use the keybinding wherever you wish (e.g. in the middle of a complex command), not just with cd.
