### ISSUE TITLE
Behaviour of fzf-f is different from fzf

### ISSUE THREAD

**Issue by RobinRamael** [andrewferrier/fzf-z#26]
For some reason, running fzf-z in my terminal using <ctrl-g> only searches through a certain subset of files, while running `fzf` itself seems to give me everything. For example, in a django project, going `fzf<CR>migrations` finds all my migrations files, while going `<ctrl-g>migrations` doesn't find anything. I don't have any env vars set and I'm on the latest version. Any idea what the problem might be?

**Comment by RobinRamael** [comment]
ok, I just realized that ofcourse fzf-z doesn't find them, as i had never visited that folder...

**Comment by andrewferrier** [comment]
Correct. `fzf-z` is based only on folders you have visited, or that fulfill the other criteria listed in README.md. Thanks!
