### ISSUE TITLE
Installing the plugin

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [andrewferrier/fzf-z#31]
Apologies if this is totally obvious, but I couldn't find the precise instruction for this in the README file or older issues. 

I'm used to being able to activate (install?) plugins using:
```
plugins=(
    git
    z
    gitignore
    command-not-found
    history-substring-search
    git-extras
    mvn
    pep8
    extract
)
```

However, when I add `fzf-z` to the above list, `[oh-my-zsh]` complains with 
```
[oh-my-zsh] plugin 'fzf-z' not found
```

I assume that's because I didn't install it first. How exactly do I do so?

**Comment by andrewferrier** [comment]
Thanks for the bug. I've expanded on `README.md` a little to provide some basic installation instructions. To answer your question - your configuration is not sufficient. What you describe is specific to plugins supplied with `oh-my-zsh`, which `fzf-z` is not. You'll need to find a way to install custom plugins. I tend to use `antibody` for this, but there are other choices.
