### ISSUE TITLE
Reverser

### ISSUE THREAD

**Issue by chew-z** [andrewferrier/fzf-z#9]
Hello,

This is not a bug just observation that fzf has --tac option so you can shed some code making plugin more compact.

No need testing for reverser and you can just replace $REVERSER in RECENTLY_USED_DIRS pipe with option --tac in  FZF_COMMAND=.... 

Still fan of fzf-z. :)

**Comment by andrewferrier** [comment]
Thanks. It appears that's actually been in fzf since 0.9.4, so hardly recent; I should have spotted it earlier. I'll take a look and make that change when I get a sec.

**Comment by andrewferrier** [comment]
So unfortunately I don't think this is going to work. It was a good idea, but only some of the inputs into fzf should be reversed - if you look at the current source you'll see it's only `$RECENTLY_USED_DIRS` it's used with. So a reverser applied at the fzf level will have the wrong effect.

Thanks - good idea though!
